### ISSUE TITLE
String {~~}  is too long

### ISSUE THREAD

**Issue by orangespoons** [Illidanz/OokamiTranslation#10]
Log:
1.5.5: https://pastebin.com/fHPV1ur4
1.6.0: https://pastebin.com/yjXgNYnC
1.7.0: https://pastebin.com/PH7tazYY

File:
- holo.nds (1st game)
- https://mega.nz/file/Wws3DQbR#edf8y35_sP7Eyix3qX0iLUIfYVqYNW0cnVG6VsvniKI
(There is a person who translates, but there are only a few lines of translation because I haven't received the translated file yet. Please understand. sorry.)

In the meantime, I have been using version 1.5.5. And today I upgraded the version.
From version 1.6.0, a lot of String {~~} is too long messages appear.

If you look at the error part of the 1.5.5 version log
([ERROR] String 焼戚原婚益拭辞 亜維 賑喰|掻戚虞壱? is too long (19/35).)
This part is the same as "アイマベルグで価格暴落中？=아이마벨그에서 가격 폭락 중이라고?" of dat_input.txt.
Maybe an error appears because the length is longer than the original text.
In other parts, it seems to be okay if the length of the translated text is slightly longer than the original text.

However, from version 1.6.0, an error seems to appear even if it is slightly longer than the original text.
Is it ok to use version 1.5.5 instead of the latest version?
And... is it normal for an error to occur in the latest version?
I couldn't determine if this was an error or an intended fix, so I opened Issues.
Thanks.

**Comment by Illidanz** [comment]
This is intended since the newer versions are checking for some data constraints, the old ones caused the game to crash when reading goods text if it was too long.
