### ISSUE TITLE
Kerning Problem

### ISSUE THREAD

**Issue by luatsenpai** [Illidanz/OokamiTranslation#13]
Hello, is there any way to fix the kerning of this game?
<img src="https://i.ibb.co/cTJtxHM/kerning.png" alt="kerning" border="0">|
<img src="https://i.ibb.co/0cjdk0R/test.png" alt="test" border="0">

**Comment by Illidanz** [comment]
Hi, you can edit the font properties and save it in a replace folder (for example data\replace\data\font\lcfont12.NFTR), the font will be replaced and the tool will read the new values for wordwrapping purposes.
