### ISSUE TITLE
Looping dialogs

### ISSUE THREAD

**Issue by arinayarina** [Illidanz/OokamiTranslation#7]
I have some problem translating the game. I use Cyrillic in my translation. Since it does not fit into the range from 0x20 to 0x7e, I use the original Cyrillic alphabet from the 0x8440 font, adding in the same assembly code that takes the correct size for each character. But I ran into a problem, some dialogs are looping. I noticed that this is possibly related to the size of the entire line before the line break. If you delete a part, then this dialog starts working. But on the other hand, I have dialogs that fit more characters per line than that, and still work. Any ideas?

I could use fontconfig.txt to replace Cyrillic with Latin characters, but they just don't fit in that range.

**Comment by Makein** [comment]
Are you translating to Russian?

**Comment by arinayarina** [comment]
> Are you translating to Russian?
> Because I made a little translation myself and adapt tool for it

Yes. How can I contact you?

**Comment by Makein** [comment]
> 
> 
> > Are you translating to Russian?
> > Because I made a little translation myself and adapt tool for it
> 
> Yes. How can I contact you?

WaYnE#1006
