### ISSUE TITLE
should I delete unk or something dirty texts?

### ISSUE THREAD

**Issue by orangespoons** [Illidanz/OokamiTranslation#8]
Hello! long time no see.
Now that I can afford it, I am working with a translator.
I have a few question about unk or something dirty texts

readme.md: 
Control codes are specified as <XX> or UNK(XXXX), they should usually be kept.

https://github.com/Illidanz/OokamiTranslation/issues/5: 
Yes you should remove any line that doesn't need a translation or looks wrong from bin_input and dat_input.

What guidelines should I follow?
Is it correct to delete all lines like below?
It seems to work normally when I delete it, but the instructions in readme.md are different, so I ask a question!

`ОUNK(0202)TYUNK(0902)/data/mapnode.dat=`
`LTUNK(0202)=`
`鏈UNK(0902)UNK(085A)UNK(0902)=`
`忝UNK(0902)=`
`LUNK(0700)=`
`LR=`
`L=`
`L_Create : Work pointor is NULL.=`
`L_Create : Work size is too small.=`
`L_Init : Already initialized.=`
etc...

**Comment by orangespoons** [comment]
first one is my fault.
I cut out all the text at the top for comparison, but the problem was caused by applying it as it is.
So I edited the title and content.

**Comment by Illidanz** [comment]
Yes, you should remove all the ones you don't need to translate, including those ones that don't really look like actual lines.
